### ISSUE TITLE
Add node package.json

### ISSUE THREAD

**Issue by zenpuppet** [kimlercorey/Triped#1]
The project needs a basic package file for installing all the various node modules.

**Comment by kimlercorey** [comment]
feel free and We can rewite the one I have locally

**Comment by kimlercorey** [comment]
cd to Triped/examples/atm-rest - first example is up at that location. From there you should be able to run:

node server.js or nodemon server.js

This first version also needs mongoDB until we get the mssql version up and running ( brew install mongodb ).
